# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for together-mcp-server
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* tsconfig.json ./
COPY src ./src

# Install and build
RUN npm install --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Ensure permissions
RUN chmod +x build/index.js

# Default command (will be overridden by MCP harness)
CMD ["node", "build/index.js"]
